config/routes.rb
Log::Application.routes.draw do

  get "move_types/new"
  get "move_types/edit"
  get "moves/new"
  get "moves/edit"
  get "moves/create"
  get "assets/new"
  get "tasks/new"
  resources :users
  resources :assets
  resources :moves
  resources :tasks
  resources :task_lists do
      resources :tasks
  end      
  resources :asset_types do
    resources :assets
  end
  resources :move_types do
    resources :moves
  end
  
  root 'welcome#index'

  

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :asset_type
  belongs_to :user
  has_many :moves

  validates :title, presence: true, length: {in: 1..120}
  # validates :asset_type_id, presence: true
  validates :user_id, presence: true
  # validates :asset_tag, numericality: {only_integer: true}
  
  # method to return the asset tag & asset type together as a string
  def asset_tag_and_asset_type
    @@type = AssetType.where(:id => self.asset_type_id).first.title
    "#{self.asset_tag}  -  #{@@type}"
  end
 
  self.per_page = 10 
end

app/models/asset_type.rb
class AssetType < ActiveRecord::Base
  has_many :assets
  has_many :moves, through: :assets

  validates :title, presence: true, length: {in: 1..64}

  self.per_page = 10
end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :user
  belongs_to :move_type
  belongs_to :asset
  
  validates :user_id, presence: true
  #validates :move_type_id, presence: true
  # validates :asset_id, presence: true, numericality:  {only_integer: true}
  validates :description, presence: true, length: {in: 1..120}
end

app/models/move_type.rb
class MoveType < ActiveRecord::Base
  has_many :moves

  validates :title, presence: true, length: {in: 1..32}

  self.per_page = 10
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :tasklist
  belongs_to :user

  validates :title, presence: true, length: {in: 1..120}
  validates :tasklist_id, presence: true
  validates :user_id, presence: true

  # return the completion value of a task as "complete" or "not complete"
  def completion_aspect
    true_value = "Completed"
    false_value = "Incomplete"
    self.complete ? true_value : false_value
  end
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  has_many :tasks
  belongs_to :user

  validates :title, presence: true, length: {in: 1..32}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assets
  has_many :moves
  has_many :task_lists
  has_many :tasks
  #has_many :tasks, through: :task_list

  self.per_page = 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def new
    @asset = Asset.new
  end
  
  def create
    @asset = Asset.create(
        params[:asset].permit(
            :title,
            :asset_type_id,
            :user_id,
            :asset_tag))
    if @asset.save 
      redirect_to assets_path
    else
      render 'assets/new'
    end
  end
  
  def index
    @assets = Asset.order('title ASC').page(params[:page])
  end
  
  def show
    @asset = Asset.find(params[:id])
  end
  
  def edit
    @asset = Asset.find(params[:id])
  end
  
  def update
  	@asset = Asset.find(params[:id])
    if @asset.update(params[:asset].permit( 
                                            :title, 
                                            :asset_type_id,
                                            :user_id,
                                            :asset_tag ))
      redirect_to @asset
  	else
	  	render 'edit'
    end
  end
end

app/controllers/move_types_controller.rb
class MoveTypesController < ApplicationController
  def new
  	@move_type = MoveType.new
  end

  def edit
    @move_type = MoveType.find params[:id]
  end
  
  def create
  	@move_type = MoveType.create(params[:move_type].permit(:title))
  	if @move_type.save
  		@status_message = 'Move type ' + @move_type.title + ' saved successfully!'
  		redirect_to move_types_path
    else
      render 'edit'
    end
  end
  
  def index
  	#@move_types = MoveType.all.sort_by! &:title
	@move_types = MoveType.order("title ASC").page(params[:page])
  end

  def show
    redirect_to move_types_path
  end  
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def new
    @move = Move.new
    #@user = User.where( :id => params[:id] ).first
    #@move_types = MoveType.select(:id, :title).sort_by! &:title
    #@assets = Asset.select(:id, :asset_tag, :asset_type_id).sort_by! &:asset_tag
  end

  def edit
    @move = Move.find params[:id]
  end

  def create
    @move = Move.create(
        params[:move].permit(
            :description,
            :user_id,
            :move_type_id))
    if @move.save
      redirect_to moves_path
    else
      render 'moves/index'
    end
  end

  def index
    @moves = Move.all.sort_by! &:created_at
  end


  def show
    redirect_to moves_path
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
	def new
		@task_list = TaskList.new
	end

	def index
		@task_lists = TaskList.all
		@tasks = Task.all
	end

	def show
		@task_list = TaskList.find(params[:id])
		# unless specified with params[:complete], only show uncomplete tasks
		params[:complete]? 
			(@task_list_tasks = Task.where(:tasklist_id => params[:id])) : 
			(@task_list_tasks = Task.where(:tasklist_id => params[:id], :complete => false))
		# sort tasks by most recent or (in a future version) another way depending on user input	
		@task_list_tasks = @task_list_tasks.order(created_at: :desc)
	end

	def create
		@task_list = TaskList.create(
			params[:task_list].permit(
				:title,
				:user_id)
		)
		if @task_list.save 
			redirect_to task_list_path @task_list.id
		end
	end

	def edit
		@task_list = TaskList.find(params[:id])
	end

	def update
		@task_list = TaskList.find(params[:id])
		if @task_list.update(params[:task_list].permit(:title,:user_id))
			redirect_to @task_list
		else
			render 'edit'
		end
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def new
		@task = Task.new
		@task_list = TaskList.find(params[:task_list_id] || 1) #if a tasklist_id is not supplied then go to the default list
	end

	def create
		@task = Task.create(
			params[:task].permit(
				:title,
				:complete,
				:completed_on,
				:user_id,
				:tasklist_id)
		)
		if @task.save
			redirect_to task_list_path(params[:tasklist_id]) 
		end
	end

	def index
		redirect_to task_lists_path
	end

	def show
		@task = Task.find(params[:id]) 
		@task_list = TaskList.find(@task.tasklist_id)
	end

	def edit
		@task = Task.find(params[:id])
	end

	def destroy 
		@task = Task.find(params[:id])
		@task_list = TaskList.where(:id => @task.tasklist_id).first
		if @task.destroy
			redirect_to task_list_path(@task_list)
		end
	end

	def update
		@task = Task.find(params[:id])
		@task_list = TaskList.find(@task.tasklist_id)

		if @task.update( params[:task].permit( :complete, :completed_on, :title, :user_id ))
			redirect_to @task_list
		else
			render 'edit'
		end
	end

private
	def post_params
		params.require(:post).permit(:title, :text) 
		# allows us to accept both text & title fields in this action
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.create(params[:user].permit(:name,:phone))
    if @user.save
      redirect_to users_path @user
    end
  end
  
  def index
    #@users = User.all.paginate(:page => params[:page], :per_page => 20)
    @users = User.order('name ASC').page(params[:page])
  end


  def show
    @user = User.find(params[:id])
    @user_assets = Asset.where(:user_id => @user.id)
    @user_tasks = Task.where(:user_id => @user.id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	  @task_list = TaskList.where( :id => 1).first
	  @tasks = Task.where(:tasklist_id => 1, :complete => false).order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asset_type_helper.rb
module AssetTypeHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/move_types_helper.rb
module MoveTypesHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/move_types/_form.html.erb
<%= simple_form_for @move_type do |f| %>
	<%= f.input :title %><br>
	<%= f.button :submit %>
<% end %>

<p><%= link_to "Cancel", moves_path %></p>

app/views/move_types/edit.html.erb
<h3>Edit Move Type</h3>
<%= render "form" %>

app/views/move_types/index.html.erb
<p class="section_links">
	<span class="section_title">Move Types</span>
	&nbsp;|&nbsp;&nbsp;
	<%= link_to 'New Type', move_types_new_path %> &nbsp;
	<%= link_to 'New Move', moves_new_path %> &nbsp;
</p>

<!-- Show all MoveType -->
<%= div_for(@move_types, class: 'move_type') do |move_type| %>
	<%= link_to move_type.title, move_type_path(move_type) %>
<% end %>
<br>
<%= will_paginate @move_types %>

app/views/move_types/new.html.erb
<h3>New Move Type</h3>
<%= render 'form' %>

app/views/move_types/show.html.erb
<h3>MoveType#Show</h3>
<p>There’s nothing here.</p>

app/views/task_lists/_form.html.erb
<%= simple_form_for @task_list do |f| %>
	<%= f.input :title %>
  	<%= f.button :submit %>
<% end %>

<%= link_to ‘Cancel’, @task_list %>

app/views/task_lists/_tasks.html.erb
<!-- render a color-coded div li for each task in the list --> 
<div class="task_list">
	<!-- check for the presence of tasks in this list -->
	<% if @task_list_tasks.count > 0  %>
		<!-- if incomplete items are shown also, print them at the bottom --> 
		<%= div_for(@task_list_tasks) do |task| %>
			<% unless task.complete  %>
			<ul>
				<li class="<%= task.completion_aspect %>">
				<p style="margin-left:2.5em;">
					<%= link_to task.title, task_path(task) %> &nbsp;
					(<%= link_to task.user.name, user_path(task.user) %>)
				</p>
				</li>
			</ul>
			<% end %>
		<% end %>
		<%= div_for(@task_list_tasks) do |task| %>
			<% if task.complete %>
			<ul>
				<li class="<%= task.completion_aspect %>">
				<p style="margin-left:2.5em;">
					<%= link_to task.title, task_path(task) %> &nbsp;
					(<%= link_to(task.user.name, user_path(task.user)) %>
					<%= ',  completed on '+task.completed_on.strftime("%m-%d-%Y") %>)
				</p>
				</li>
			</ul>
			<% end %>
		<% end %>

	<% else %> <!-- if no tasks are present in this list, then say so. -->
		<div>
			<p style="margin-left:2.5em;">
			<em>No Tasks</em></p>
		</div>
	<% end %>
</div>

app/views/task_lists/edit.html.erb
<h3>Edit List</h3>
<%= render "task_lists/form" %>

app/views/task_lists/index.html.erb
<p class="section_links">
<span class="section_title">Task Lists</span>
&nbsp;|&nbsp;&nbsp;
<%= link_to 'New List', {action: "new", method: :show } %>&nbsp;
<%= link_to 'New Task', new_task_path %>
</p>

<% if @task_lists.count > 0 %>
	<%= div_for(@task_lists, class: 'task_list') do |task_list| %>
		<h4 style="margin-left:1em;margin-bottom:5px;"><%= link_to task_list.title, task_list_path(task_list) %></h4>
		<% @task_list_tasks = @tasks.where(
						:tasklist_id => task_list.id, 
						:complete => false)
						.limit(5)
						.order(created_at: :desc) %>
		<%= render "tasks" %>
	<% end %>
<% else %>
	<div>
		<p><em>No Lists</em></p>
	</div>
<% end %>

app/views/task_lists/new.html.erb
<h3>New Task List</h3>
<%= render "form" %>

app/views/task_lists/show.html.erb
<p class="section_links">
	<span class="section_title"><%= @task_list.title %></span>
	<%= render "shared/spacer" %>
	<%= link_to 'New Task', new_task_list_task_path(@task_list) %>&nbsp;
	<%= link_to 'Edit', edit_task_list_path %>&nbsp;
	<%= if params[:complete] then link_to 'Hide Complete',@task_list end %>
		<%= if !params[:complete] then link_to 'Show Completed', task_list_path(@task_list.id, :complete => true) end %>	&nbsp;
		<%= 'Sort ASC' %>&nbsp;
		<%= 'Sort DESC' %>&nbsp;
		<%= 'Delete List' %>&nbsp;
</p>

<!-- render the tasks in this list, taking into account the 'complete' flag.
<%= render "tasks" %>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
	<%= f.hidden_field :tasklist_id, {:value => (params[:task_list_id] || 1)} %>
	<% unless @task.complete %>
		<%= f.hidden_field :complete, {:value => false} %>
	<% end %>

    <%= f.input :title %>
	<%= f.input :user_id,  collection: User.all, :prompt => true %>
	<%= f.button :submit %>
<% end %>

<%= link_to ‘Cancel’, @task %>

app/views/tasks/edit.html.erb
<h3>Edit Task</3>
<%= render "form" %>

app/views/tasks/new.html.erb
<%= render "shared/navigation_top" %>
<h3>New Task</h3>
<!-- Render new Task form -->
<%= render "form" %>

app/views/tasks/show.html.erb
<%= render "shared/navigation_top" %>
<p class="section_links">
	<span class="section_title"><%= @task.title %></span>
	&nbsp;|&nbsp;&nbsp;
	(<%= @task.completion_aspect %>)&nbsp;
	<%= link_to "Edit", edit_task_path(@task) %>
</p>

	<!-- Mark as complete button -->
	<%= form_for @task do |f| %>
		<%= f.hidden_field :completed_on, { :value => Time.now } %>
		<%= f.hidden_field :complete, { :value => true } %> 
		<%= f.hidden_field :user_id, { :value => @task.user_id} %> 
		<%= button_to "Mark Complete", {action: "update", id: @task.id}, method: :patch %>
	<% end %>
	<!-- delete button -->
	<%= button_to "Delete", {action: "destroy", id: @task.id}, method: :delete, data: {confirm: "Are you sure?"} %>

app/views/tasks/update.html.erb
<%= render "shared/navigation_top" %>
<h3>Task#Update</h3>
<p>This action is not complete.</p> 

app/views/welcome/_project_notes.html.erb
  <h3>Project Notes:</h3>
  <ol>
  <!-- USERS -->
  <li>
  <p><%= link_to 'Users', users_path %></p>
  <p>Status: working / on hold.</p>
  <p>Paginated: yes</p>
  </li>
  <!-- MOVES -->
  <li>
  <p><%= link_to 'Moves', moves_path %></p>
  <p>Status: working / on hold.</p>
  <p>Paginated: No</p>
  </li>
  <!-- MOVE TYPES -->
  <li>
  <p><%= link_to 'Move Types', move_types_path %></p>
  <p>Status: working / on hold.</p>
  <p>Paginated: Yes</p>
  </li>
  <!-- ASSETS -->  
  <li>
  <p><%= link_to 'Assets', assets_path %></p>
  <p>Status: working / on hold.</p>
  <p>Paginated: Yes</p>
  </li>
  <!-- ASSET TYPES -->
  <li>
  <p><%= link_to 'Asset Types', asset_types_path %></p>
  <p>Status: working / on hold.</p></li>
  <p>Paginated: Yes</p>
  <!-- TASK LISTS -->
  <li>
  <p><%= link_to 'Task Lists', task_lists_path %></p>
  <p>Status: working / in progress</p></li>
  <p>Paginated: No</p>
  <!-- TASKS -->
  <li>
  <p><%= link_to 'Tasks', task_lists_path %></p>
  <p>Status: mostly working / in progress</p></li>
  <p>Paginated: No</p>
</ol>
</div>

app/views/welcome/_todo_list.html.erb
<!-- Automatic List -->
<% if @task_list then %>
	<h3><%= link_to @task_list.title, task_list_path(@task_list) %></h3>
	<% if @tasks.count > 0 then %>
	<ul>
		<%= div_for @tasks do |task| %>
			<li><%= task.title %></li>
		<% end %></ul>
	<% end %>
<%= link_to 'New Task', "task_lists/1/tasks/new" %>
<% else %>
	<h3>No Default Task List</h3>
<% end %>
<hr>
<p><a href="https://github.com/codegard1/log/issues">View Issues on Github</a></p>

app/views/welcome/index.html.erb
<h3>Log Lady 3.800b</h3>
<h4>Welcome to the index!</h4>
<hr>

<table> 
	<tr>
		<td width=“40%”>
			<%= render 'project_notes' %>
		</td>
		<td width=“60%”>
			<%= render 'todo_list' %>
		</td>
	</tr>
</table>