config/routes.rb
Log::Application.routes.draw do

  get "move_types/new"
  get "move_types/edit"
  get "moves/new"
  get "moves/edit"
  get "moves/create"
  get "assets/new"
  get "tasks/new"
  resources :users
  resources :assets
  resources :moves
  resources :tasks
  resources :task_lists do
      resources :tasks
  end      
  resources :asset_types do
    resources :assets
  end
  resources :move_types do
    resources :moves
  end
  
  root 'welcome#index'

  

end

app/controllers/asset_types_controller.rb
class AssetTypesController < ApplicationController
  before_action :AssetType, only: [:create, :destroy]
  
  def new
    @asset_type = AssetType.new
  end
  
  def create
    @asset_type = AssetType.create(params[:asset_type].permit(:title,:group))
    if @asset_type.save 
      redirect_to asset_types_path
    end
  end

  def show
    @asset_type = AssetType.where(:id => params[:id]).first
    @assets_by_type = Asset.where(:asset_type_id => params[:id]).order("created_at DESC")
  end  
  
  def index
    @asset_types = AssetType.order(:title).page(params[:page])
    @asset_type_groups = AssetType.pluck(:group).sort
  end
end

app/helpers/asset_type_helper.rb
module AssetTypeHelper
end

app/views/asset_types/_form.html.erb
<%= simple_form_for @asset_type do |f| %>
    <%= f.input :title %><br>
    <%= f.input :group %><br>
    <%= f.button :submit %>
<% end %>

<p><%= link_to "Cancel", @asset_type %></p>

app/views/asset_types/edit.html.erb
<h3>Edit Asset Type</h3>
<%= render 'form' %>

app/views/asset_types/index.html.erb
<p class="section_links">
	<span class="section_title">Asset Types</span>
	&nbsp;|&nbsp;&nbsp;
	<%= link_to "New Type", new_asset_type_path %> &nbsp; 
	<%= link_to "New Asset", new_asset_path %> &nbsp;
</p>


<!-- show all AssetType -->
<% if @asset_types.count > 0 %>
	<%= div_for(@asset_types, class: 'asset_type') do |asset_type| %>
		<span>
			<strong><%= link_to asset_type.title, asset_type_path(asset_type.id) %></strong> &nbsp;
			(<em><%= asset_type.group %></em>)
		</span>
	<% end %>    
<% end %>    
<%= will_paginate @asset_types %>

app/views/asset_types/new.html.erb
<h3>New Asset Type</h3>
<%= render "form" %>

app/views/asset_types/show.html.erb
<!-- show asset type -->
<%= div_for( @asset_type ) do %>
	<!-- link to asset title, show records from ASSET that have this title -->
	<div>
		<h2><%= @asset_type.group %></h2>
		<p style='margin-left:2em'><%= link_to @asset_type.title, asset_type_path(@asset_type) %></p>
	</div>
<% end %>

<!-- if an object containing assets of type @asset_type is passed by the
controller, then print divs for each object -->
<% if @assets_by_type %>
	<%= div_for( @assets_by_type ) do |asset| %>
		<%= link_to asset.user.name, user_path(asset.user_id) %><hr>	
		<%= asset.asset_tag %>
		<%= link_to 'Edit', edit_asset_path(asset.id) %><br>
		<%= asset.updated_at %>
	<% end %>
<% end %>

<%= link_to 'New ' + @asset_type.title, new_asset_path(@asset_type.id) %>

<!-- if an object containing assety type groups 
then print a div for each grouping -->