config/routes.rb
Log::Application.routes.draw do

  get "move_types/new"
  get "move_types/edit"
  get "moves/new"
  get "moves/edit"
  get "moves/create"
  get "assets/new"
  get "tasks/new"
  resources :users
  resources :assets
  resources :moves
  resources :tasks
  resources :task_lists do
      resources :tasks
  end      
  resources :asset_types do
    resources :assets
  end
  resources :move_types do
    resources :moves
  end
  
  root 'welcome#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assets
  has_many :moves
  has_many :task_lists
  has_many :tasks
  #has_many :tasks, through: :task_list

  self.per_page = 10
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.create(params[:user].permit(:name,:phone))
    if @user.save
      redirect_to users_path @user
    end
  end
  
  def index
    #@users = User.all.paginate(:page => params[:page], :per_page => 20)
    @users = User.order('name ASC').page(params[:page])
  end


  def show
    @user = User.find(params[:id])
    @user_assets = Asset.where(:user_id => @user.id)
    @user_tasks = Task.where(:user_id => @user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_assets.html.erb
<!-- print user name -->
<h4><span>
    Assets belonging to <%= @user.name %></span></h4>

<!-- Print ordered list of user asset records -->
<% if @user_assets.count >= 1 %>
  <%= div_for(@user_assets) do |user_asset| %>
        <span><em><%= user_asset.title or "None" %></em></span><br>
	<span><em><%= user_asset.asset_type.title or 'No type given' %></em></span><br>
        <span><em><%= user_asset.asset_tag or 'No asset tag' %></em></span>
  <% end %>
<% else %>
  <p style="margin-left:2em;">
    <em>No asset records found</em>
  </p>
<% end %>
<span>
	<%= link_to 'New Asset', new_asset_path(:id => @user) %>
</span>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name, label: 'username' %><br>
  <%= f.input :phone %><br>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Cancel', @user %>

app/views/users/_old.html.erb
<%= div_for(@users) do |user| %>
    <span>
      <strong><%= link_to user.name, user_path(user) %></strong>
    </span>
    <br>
    <span>
      Phone: <strong><%= user.phone or 'None' %></strong>
    </span>
    <br>
    <span>
      Assets owned: <strong><%= user.assets.count %></strong>
    </span>
    <br>
    <br>
    <%= link_to 'New asset', new_asset_path(user) %>&nbsp;
    <%= link_to 'New Move', new_move_path(user) %>&nbsp;
<% end %>

app/views/users/_tasks.html.erb
<h4>Tasks for <%= @user.name %></h4>
<!-- render a color-coded div li for each task in the list --> 
<% if @user_tasks.count > 0 then %>
	<%= div_for(@user_tasks) do |task| %>
		<ul>
			<li class="<%= task.completion_aspect %>">
			<p style="margin-left:2.5em;">
				<%= link_to task.title, task_path(task) %>
			</p>
			</li>
		</ul>
	<% end %>
<% else %>
	<p style="margin-left:2.5em;">
	  <em>No Tasks</em><br>
	</p>
<% end %>

<span>
	<%= link_to 'New Task', new_task_path(:id => @user) %>
</span>

app/views/users/edit.html.erb
<h3>Edit User</h3>
<% redirect_to users_path %>

app/views/users/index.html.erb
<!-- Show all users -->
<p class="section_links">
	<span class="section_title">Users</span>
	&nbsp;|&nbsp;&nbsp;
	<%= link_to 'New User', new_user_path %> &nbsp;
</p>

<%= div_for @users, class: 'user'  do |user| %>
	<%= link_to user.name, user_path(user) %>
<% end %>
<br>
<%= will_paginate @users %>

app/views/users/new.html.erb
<h3>New User</h3>
<%= render "form" %>
<%= link_to 'Cancel', users_path %>

app/views/users/show.html.erb
<%= render "shared/navigation_top" %>

<!-- Print List of assets belonging to user -->
<%= render "users/assets" %>
<hr>
<!-- Print list of user-owned tasks -->
<%= render "users/tasks" %>