config/routes.rb
Log::Application.routes.draw do

  get "move_types/new"
  get "move_types/edit"
  get "moves/new"
  get "moves/edit"
  get "moves/create"
  get "assets/new"
  get "tasks/new"
  resources :users
  resources :assets
  resources :moves
  resources :tasks
  resources :task_lists do
      resources :tasks
  end      
  resources :asset_types do
    resources :assets
  end
  resources :move_types do
    resources :moves
  end
  
  root 'welcome#index'

  

end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :user
  belongs_to :move_type
  belongs_to :asset
  
  validates :user_id, presence: true
  #validates :move_type_id, presence: true
  # validates :asset_id, presence: true, numericality:  {only_integer: true}
  validates :description, presence: true, length: {in: 1..120}
end

app/models/move_type.rb
class MoveType < ActiveRecord::Base
  has_many :moves

  validates :title, presence: true, length: {in: 1..32}

  self.per_page = 10
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def new
    @move = Move.new
    #@user = User.where( :id => params[:id] ).first
    #@move_types = MoveType.select(:id, :title).sort_by! &:title
    #@assets = Asset.select(:id, :asset_tag, :asset_type_id).sort_by! &:asset_tag
  end

  def edit
    @move = Move.find params[:id]
  end

  def create
    @move = Move.create(
        params[:move].permit(
            :description,
            :user_id,
            :move_type_id))
    if @move.save
      redirect_to moves_path
    else
      render 'moves/index'
    end
  end

  def index
    @moves = Move.all.sort_by! &:created_at
  end


  def show
    redirect_to moves_path
  end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= simple_form_for @move do |f| %>
	<!-- text field for description -->
	<%= f.input :description, as: :text %><br>
	<!-- selection field for User -->
	<%= f.input :user_id, collection: User.all, :value_method => :id, :prompt => true %><br>
	<!-- Selection field for Move Type -->
	<%= f.input :move_type_id, collection: MoveType.all, :value_method => :id, :prompt => true %><br>
	<!-- Selection field for existing Assets-->
	<%= f.input :asset_id, collection: Asset.all, :value_method => :id, :prompt => true %><br>
	<%= f.button :submit  %>
<% end %>

<%= link_to 'Cancel', @move %>

app/views/moves/edit.html.erb
<h3>Edit Move</h3>
<%= render ‘form’ %>

app/views/moves/index.html.erb
<p class="section_links">
	<span class="section_title">Moves</span>
	&nbsp;|&nbsp;&nbsp;	
	<%= link_to 'New Move', new_move_path %> &nbsp;
	<%= link_to 'New Type', new_move_type_path %>
<p>

<!-- Show All Moves -->
<% if @moves.count > 0 %>
	<%= div_for(@moves, class: 'move') do |move| %>
		<p class="date_created"> &nbsp; 
			<%= Time.at(move.created_at.to_i).to_date.inspect %></p>
		<p class="description">&nbsp; 
			<%= link_to move.description, move_path(move) %></p>
		<p class="user_name">&nbsp; 
    			<%= link_to move.user.name, user_path(move.user) %></p>
		<p class="move_type">&nbsp; 
			<%= link_to move.move_type.title, move_type_path(move.move_type) %></p>
		<p class="asset_type">&nbsp; 
			<%= link_to move.asset.asset_type.title, asset_type_path(move.asset.asset_type) %></p>
		<p class="asset_tag">&nbsp;
			<%= link_to move.asset.asset_tag, asset_path(move.asset.asset_tag) %></p>
	<% end %>
<% end %>

app/views/moves/new.html.erb
<h3>New Move</h3>
<%= render "form" %>

app/views/moves/show.html.erb
<h3>Move#Show</h3>
<p>There’s nothing here.</p>